version: "3.8"

networks:
  redisn:
    driver: bridge

services:
  # Servicio para el recolector de datos de Waze
  waze-data-collector:
    build: ./waze-data-collector
    container_name: waze_data_collector
    networks:
      - redisn
    volumes:
      - ./waze-data-collector:/app
    environment:
      - ELASTICSEARCH_URL=https://my-elasticsearch-project-f2727a.es.us-east-1.aws.elastic.cloud:443
      - ELASTICSEARCH_API_KEY=OVlYTEdaY0JBMURWU1pMNHZEXzM6ejBwVFFLcklSelk3UFNSSXdDajZ0QQ==
    #depends_on:
      #- data-storage

  # Servicio para el almacenamiento de datos
  data-storage:
    build: ./data-storage
    container_name: data_storage
    ports:
      - "5001:5001"
    networks:
      - redisn
    environment:
      - ELASTICSEARCH_URL=https://my-elasticsearch-project-f2727a.es.us-east-1.aws.elastic.cloud:443
      - ELASTICSEARCH_API_KEY=OVlYTEdaY0JBMURWU1pMNHZEXzM6ejBwVFFLcklSelk3UFNSSXdDajZ0QQ==
    depends_on:
      - waze-data-collector

  # Servicio para Redis (Cache)
  redis:
    image: bitnami/redis:latest
    restart: always
    container_name: redis_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--maxmemory 2mb --maxmemory-policy allkeys-random
    ports:
      - "6379:6379"
    volumes:
      - redis_data_1:/bitnami/redis/data
    networks:
      - redisn

  # Servicio para la interfaz de administración de Redis
  redis-admin:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redis_admin
    volumes:
      - redis-insight:/data
    ports:
      - "5540:5540"
    networks:
      - redisn
    depends_on:
      - redis
      - waze-data-collector

  # Servicio para el generador de tráfico (Processing)
  traffic-generator:
    build: ./traffic-generator
    container_name: traffic_generator
    depends_on:
      - redis
      - waze-data-collector
    networks:
      - redisn
    restart: always
    environment:
      - ELASTICSEARCH_URL=https://my-elasticsearch-project-f2727a.es.us-east-1.aws.elastic.cloud:443
      - ELASTICSEARCH_API_KEY=OVlYTEdaY0JBMURWU1pMNHZEXzM6ejBwVFFLcklSelk3UFNSSXdDajZ0QQ==

  # Servicio para el sistema de caché (Filtering)
  query-cache:
    build: ./query-cache
    container_name: query_cache
    restart: always
    ports:
      - "5000:5000"
    networks:
      - redisn
    volumes:
      - ./query-cache:/app
    depends_on:
      - redis
      - traffic-generator
    environment:
      - ELASTICSEARCH_URL=https://my-elasticsearch-project-f2727a.es.us-east-1.aws.elastic.cloud:443
      - ELASTICSEARCH_API_KEY=OVlYTEdaY0JBMURWU1pMNHZEXzM6ejBwVFFLcklSelk3UFNSSXdDajZ0QQ==

  # Servicio para Apache Pig (Data Processing)
  # pig:
  #   build: ./pig
  #   container_name: pig
  #   volumes:
  #     - ./scripts:/pig-scripts
  #   entrypoint: ["pig", "-x", "local", "/pig-scripts/process_waze.pig"]
  #   networks:
  #     - redisn
  #   depends_on:
  #     - waze-data-collector
  #   environment:
  #     - ELASTICSEARCH_URL=https://my-elasticsearch-project-f2727a.es.us-east-1.aws.elastic.cloud:443
  #     - ELASTICSEARCH_API_KEY=OVlYTEdaY0JBMURWU1pMNHZEXzM6ejBwVFFLcklSelk3UFNSSXdDajZ0QQ==

volumes:
  redis_data_1:
    driver: local
  redis-insight:
